#!/bin/bash
# SPDX-License-Identifier: MIT
# ============================================================================
# Phoenix-8086 — Build the demo web site
# ============================================================================
#
# Assembles a static site in site/ that boots the real kernel in the
# visitor's browser (v86 emulator) and shows it on the dashboard:
#
#   site/                the dashboard, configured for emulator mode
#   site/emulator/       v86, its BIOS images, and the floppy image
#
# Needs: a built floppy image (make all), npm, curl, sha256sum.
# The emulator and BIOS files are third-party and are fetched here, not
# kept in the repository; site/emulator/NOTICE.txt lists their licences.
#
# Try it locally:  python3 -m http.server 8080 --directory site
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SITE="$PROJECT_DIR/site"
IMAGE="$PROJECT_DIR/build/phoenix8086.img"

V86_VERSION="0.5.469"
BIOS_BASE="https://raw.githubusercontent.com/copy/v86/master/bios"
SEABIOS_SHA256="73e3f359102e3a9982c35fce98eb7cd08f18303ac7f1ba6ebfbe6cdc1c244d98"
VGABIOS_SHA256="a4bc0d80cc3ca028c73dafa8fee396b8d054ce87ebd8abfbd31b06b437607880"

if [ ! -f "$IMAGE" ]; then
    echo "ERROR: $IMAGE not found. Run 'make all' first."
    exit 1
fi

rm -rf "$SITE"
mkdir -p "$SITE/emulator"

# ── Dashboard ───────────────────────────────────
cp "$PROJECT_DIR"/dashboard/*.html "$PROJECT_DIR"/dashboard/*.css "$PROJECT_DIR"/dashboard/*.js "$SITE/"
cp -r "$PROJECT_DIR/dashboard/locales" "$SITE/locales"

cat > "$SITE/config.js" <<'CONFIG'
// Generated by tools/build_site.sh: this site runs the kernel in the page.
window.PhoenixConfig = {
    emulator: true,
};
CONFIG

# ── Emulator ────────────────────────────────────
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

(cd "$WORK" && npm install --silent --no-audit --no-fund "v86@$V86_VERSION")
cp "$WORK/node_modules/v86/build/libv86.js" "$WORK/node_modules/v86/build/v86.wasm" "$SITE/emulator/"

fetch_bios() {
    local name="$1" sum="$2"
    curl -fsSL -o "$SITE/emulator/$name" "$BIOS_BASE/$name"
    echo "$sum  $SITE/emulator/$name" | sha256sum -c --quiet -
}
fetch_bios seabios.bin "$SEABIOS_SHA256"
fetch_bios vgabios.bin "$VGABIOS_SHA256"

cp "$IMAGE" "$SITE/emulator/phoenix8086.img"

cat > "$SITE/emulator/NOTICE.txt" <<NOTICE
Third-party files in this directory

libv86.js, v86.wasm   v86 $V86_VERSION, https://github.com/copy/v86
                      BSD 2-Clause License
seabios.bin           SeaBIOS, https://www.seabios.org
                      GNU LGPL version 3; source at the address above
vgabios.bin           VGABIOS (Bochs/LGPL VGA BIOS), as distributed with v86
                      GNU LGPL; source at https://github.com/copy/v86/tree/master/bios

phoenix8086.img       Phoenix-8086 boot floppy, MIT License
NOTICE

echo "Site built in $SITE ($(du -sh "$SITE" | cut -f1))"
